Repository opensrp/opensrp-client-core, pull requests merged in 2020-05, with the labels that each got.

#510 Add unit tests
  opensrp-app/src/test/java/org/smartregister/commonregistry/CommonObjectFilterOptionTest.java
  opensrp-app/src/test/java/org/smartregister/service/FormSubmissionServiceTest.java
  opensrp-app/src/test/java/org/smartregister/service/HTTPAgentTest.java
Labels: Testing Tuesday

#514 Fix logical bug that causes blank entity ids to be processed
  gradle.properties
  opensrp-app/src/main/java/org/smartregister/util/JsonFormUtils.java
Labels: Priority: High, bug

#516 Add SmartRegisterQueryBuilder unit tests
  opensrp-app/src/main/java/org/smartregister/cursoradapter/SmartRegisterQueryBuilder.java
  opensrp-app/src/test/java/org/smartregister/adapter/SmartRegisterQueryBuilderTest.java
  opensrp-app/src/test/java/org/smartregister/commonregistry/mockactivities/HouseHoldSmartRegisterFragment.java
Labels: Testing Tuesday

#512 BaseRegisterFragment : Add unit tests
  opensrp-app/src/main/java/org/smartregister/view/fragment/BaseRegisterFragment.java
  opensrp-app/src/test/java/org/smartregister/TestApplication.java
  opensrp-app/src/test/java/org/smartregister/view/fragment/BaseRegisterFragmentTest.java
Labels: Testing Tuesday

#518 Add tests for ClientProcessorForJava#processCaseModel
  opensrp-app/src/test/java/org/smartregister/sync/ClientProcessorForJavaTest.java
Labels: Testing Tuesday

#517 Add JsonFormUtils tests
  opensrp-app/src/test/java/org/smartregister/util/JsonFormUtilsTest.java
Labels: Testing Tuesday

#522 Allow access to shared preferences from AllSettings
  gradle.properties
  opensrp-app/src/main/java/org/smartregister/repository/AllSettings.java
  opensrp-app/src/test/java/org/smartregister/repository/AllSettingsTest.java
Labels: enhancement

#530 Added SmartRegisterQueryBuilder tests
  opensrp-app/src/test/java/org/smartregister/adapter/SmartRegisterQueryBuilderTest.java
Labels: Testing Tuesday

#534 Added AllCommonsRepository tests
  opensrp-app/src/test/java/org/smartregister/commonregistry/AllCommonsRepositoryTest.java
Labels: Testing Tuesday

#531 Add test for org.smartregister.sync.ClientProcessorForJava#processField
  opensrp-app/src/main/java/org/smartregister/sync/ClientProcessorForJava.java
  opensrp-app/src/test/java/org/smartregister/sync/ClientProcessorForJavaTest.java
Labels: Testing Tuesday
