Repository opensrp/opensrp-client-core, pull requests merged in 2021-02, with the labels that each got.

#738 Add ProfileNavigationController tests
  opensrp-app/src/main/java/org/smartregister/Context.java
  opensrp-app/src/main/java/org/smartregister/CoreLibrary.java
  opensrp-app/src/main/java/org/smartregister/view/activity/mock/LoginActivityMock.java
  opensrp-app/src/test/java/org/smartregister/BaseRobolectricUnitTest.java
  opensrp-app/src/test/java/org/smartregister/BaseUnitTest.java
  opensrp-app/src/test/java/org/smartregister/util/UtilsTest.java
  opensrp-app/src/test/java/org/smartregister/view/UnitTest.java
  opensrp-app/src/test/java/org/smartregister/view/controller/ProfileNavigationControllerTest.java
  opensrp-app/src/test/java/org/smartregister/view/receiver/ConnectivityChangeReceiverTest.java
Labels: Testing Tuesday

#733 Add test for Context class
  opensrp-app/src/test/assets/test_file.txt
  opensrp-app/src/test/java/org/smartregister/ContextRobolectricTest.java
  opensrp-app/src/test/java/org/smartregister/util/UtilsTest.java
Labels: Testing Tuesday

#743 Add Utils and SyncUtils tests
  opensrp-app/src/main/java/org/smartregister/util/SyncUtils.java
  opensrp-app/src/main/java/org/smartregister/util/Utils.java
  opensrp-app/src/test/assets/app.properties
  opensrp-app/src/test/java/org/smartregister/util/SyncUtilsRobolectricTest.java
  opensrp-app/src/test/java/org/smartregister/util/UtilsTest.java
Labels: Testing Tuesday

#750 Bug fix return failure if API returns an error code
  gradle.properties
  opensrp-app/src/main/java/org/smartregister/service/HTTPAgent.java
  opensrp-app/src/test/java/org/smartregister/service/HTTPAgentTest.java
Labels: Priority: High, bug

#749 Upgrade plan evaluator
  gradle.properties
  opensrp-app/build.gradle
  opensrp-app/src/main/java/org/smartregister/repository/TaskRepository.java
  opensrp-app/src/main/java/org/smartregister/repository/dao/EventDaoImpl.java
  opensrp-app/src/main/java/org/smartregister/repository/dao/TaskDaoImpl.java
  opensrp-app/src/main/java/org/smartregister/service/HTTPAgent.java
  opensrp-app/src/test/java/org/smartregister/repository/dao/TaskDaoImplTest.java
  opensrp-app/src/test/java/org/smartregister/service/HTTPAgentTest.java
  opensrp-app/src/test/java/org/smartregister/sync/intent/ExtendedSyncIntentServiceTest.java
Labels: Dynamic Tasking
